Magento2 502 add currencies
shopgate/magento2-website-sample-data pull request #2
Opened 2020-01-09 18:28 UTC by augsteyer

Read readme for changes

2020-01-10 07:00 UTC, andre-kraus requested changes

2020-01-10 07:00 UTC, andre-kraus commented on src/Model/Website.php
> +     */
All the other PHPDocs are just one liners.

2020-01-10 16:26 UTC, augsteyer commented
Yup, I am happy now. Should have prolly not ventured that deep in the uninstall routines.

2020-01-13 07:55 UTC, andre-kraus approved these changes

2020-01-13 13:57 UTC, merged